// This file contains arrays of feedback strings categorized into positive, negative, and neutral feedbacks.

export const positiveFeedbacks: string[] = [
	"Great service, very satisfied!",
	"Excellent product quality!",
	"Fast delivery, highly recommend!",
	"Customer support was very helpful.",
	"Amazing experience, will buy again.",
	"Loved the user-friendly interface.",
	"Fantastic value for money.",
	"The team was very responsive.",
	"Exceeded my expectations!",
	"Very happy with my purchase.",
	"The app is very intuitive.",
	"Superb customer service.",
	"The product works perfectly.",
	"Very pleased with the results.",
	"The website is easy to navigate.",
	"Great discounts and offers.",
	"The packaging was excellent.",
	"The instructions were clear.",
	"The product arrived on time.",
	"The quality is top-notch.",
];

export const negativeFeedbacks: string[] = [
	"Very disappointed with the service.",
	"The product quality is poor.",
	"Delivery was very slow.",
	"Customer support was unhelpful.",
	"Terrible experience, won't buy again.",
	"The interface is confusing.",
	"Not worth the money.",
	"The team was unresponsive.",
	"Did not meet my expectations.",
	"Unhappy with my purchase.",
	"The app is very buggy.",
	"Poor customer service.",
	"The product doesn't work.",
	"Not pleased with the results.",
	"The website is hard to navigate.",
	"No discounts or offers.",
	"The packaging was damaged.",
	"The instructions were unclear.",
	"The product arrived late.",
	"The quality is subpar.",
];

export const neutralFeedbacks: string[] = [
	"The service was okay.",
	"Product quality is average.",
	"Delivery time was acceptable.",
	"Customer support was decent.",
	"An average experience.",
	"The interface is alright.",
	"Fair value for money.",
	"The team was moderately responsive.",
	"Met my expectations.",
	"Satisfied with my purchase.",
	"The app is functional.",
	"Customer service was fine.",
	"The product works as expected.",
	"Results are satisfactory.",
	"The website is usable.",
	"Some discounts available.",
	"The packaging was adequate.",
	"The instructions were fine.",
	"The product arrived on time.",
	"The quality is acceptable.",
];
