name: tests

on:
  workflow_call:

jobs:
  cdk-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: ./cdk/package-lock.json
      - name: Install cdk format
        run: npm ci
      - name: run test
        run: npm run test

  backend-type-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: ./backend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Check type
        run: npm run type-check